version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch

    steps:
      - checkout
      - run: ./mvnw -Dmaven.test.skip=true clean package
      - persist_to_workspace:
         root: ./
         paths:
           - target/
      - setup_remote_docker:
          version: 19.03.13

      # build and push Docker image
      - run: |
          TAG=3.0
          sudo docker build -t $DOCKERHUB_USERNAME/gitops-foundations:$TAG --build-arg JAR_FILE=*.jar .
          echo $DOCKERHUB_PASSWORD | sudo docker login -u $DOCKERHUB_USERNAME --password-stdin
          sudo docker push $DOCKERHUB_USERNAME/gitops-foundations:$TAG
workflows:
  main:
    jobs:
      - build:
          context: DockerHub
